const howToUseApp = [
    {
      title: " 1. Sign in",
      info: "Ola is India’s largest mobility r hundreds of millions of consumers and over 1.5 million driver-partnersnt ore mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola Financial Services and a range of owned food brands through India’s ore mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola Financial Services and a range of owned food brands through India’s largest network of kitchens under its Food business youth. With its acquisition of Ridlr.largest network of kitchens under its Food business youth. With its acquisition of Ridlr.business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola"
    },
    {
      title: "2. Search for your destination",
      info: "Ola’s core mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments ore mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola Financial Services and a range of owned food brands through India’s ore mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola Financial Services and a range of owned food brands through India’s ore mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola Financial Services and a range of owned food brands through India’s largest network of kitchens under its Food business youth. With its acquisition of Ridlr.largest network of kitchens under its Food business youth. With its acquisition of Ridlr.largest network of kitchens under its Food business youth. With its acquisition of Ridlr. through Ola Financial Services and a range of owned food brands through India’s largest network of kitchens under its Food business youth. With its acquisition of Ridlr.",
    },
    {
      title: "3. Send payment request",
      info: "investment in Vogo, a dockless scooter sharing solution, Ola is looking to build mobility for the next billion Indians. Ola also extends its consumer offerings like micro-insurance and credit led payments through Ola Financial Services and ore mobility offering in India is supplemented by its electric-vehicle arm, Ola Electric; India’s largest fleet management business, Ola Fleet Technologies and Ola Skilling, that aims to enable millions d payments through Ola Financial Services and a range of owned food brands through India’s largest network of kitchens under its Food business youth. With its acquisition of Ridlr. a range of owned food brands through India’s largest network of kitchens under its Food business.",
    },
  ];
  
  export default howToUseApp;